#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp "pod-babashka-lanterna" /tmp/release

VERSION=$(cat resources/POD_BABASHKA_LANTERNA_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-$lanterna-$VERSION-$BABASHKA_PLATFORM-amd64.zip" "pod-babashka-$lanterna"

## cleanup

rm "pod-babashka-$lanterna"
