#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true
export PATH=$GRAALVM_HOME/bin:$PATH

VERSION=$(cat resources/POD_BABASHKA_LANTERNA_VERSION)

JAR="target/pod-babashka-lanterna-$VERSION-standalone.jar"

java -version
lein "do" clean, uberjar

args=("-jar" "$JAR"
      "-H:Name=pod-babashka-lanterna"
      "-H:+ReportExceptionStackTraces"
      "-J-Dclojure.spec.skip-macros=true"
      "-J-Dclojure.compiler.direct-linking=true"
      "-H:IncludeResources=POD_BABASHKA_LANTERNA_VERSION"
      "--initialize-at-build-time"
      "-H:Log=registerResource:"
      "-H:EnableURLProtocols=http,https"
      "--enable-all-security-services"
      "-H:+JNI"
      "--verbose"
      "--no-fallback"
      "--no-server"
      "--report-unsupported-elements-at-runtime"
      "-J-Xmx4500m")

BABASHKA_STATIC=${BABASHKA_STATIC:-}
BABASHKA_MUSL=${BABASHKA_MUSL:-}

if [ "$BABASHKA_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$BABASHKA_MUSL" = "true" ]; then
        args+=("--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    else
        # see https://github.com/oracle/graal/issues/3737
        args+=("-H:+StaticExecutableWithDynamicLibC")
    fi
fi

"$GRAALVM_HOME/bin/native-image" "${args[@]}" "$@"
